development:
  adapter: mysql2
  database: faye_chat
  username: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: faye_chat_test
  username: root
  password:
  pool: 5
  timeout: 5000